accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.signup, name='register'),
    path('profile/', views.profile, name='profile'),
  
    
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('<int:pk>/', views.article_detail, name='article_detail'),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('tests/', views.test_list, name='test_list'),
    path('<int:pk>/', views.test_detail, name='test_detail'),
    path('<int:pk>/result/', views.test_result, name='test_result'),
    path('statistics/', views.statistics, name='statistics'),
]

quizsite/urls.py
from os import name
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import logout_view

from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('articles/', include('articles.urls', namespace='articles')),
    path('logout/', logout_view, name='logout'),
    path('', include('quiz.urls', namespace='quiz')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Test(models.Model):
    DIFFICULTY_EASY = 'E'
    DIFFICULTY_MEDIUM = 'M'
    DIFFICULTY_HARD = 'H'

    DIFFICULTY_CHOICES = [
        (DIFFICULTY_EASY, 'Легкая'),
        (DIFFICULTY_MEDIUM, 'Средняя'),
        (DIFFICULTY_HARD, 'Сложная'),
    ]

    title = models.CharField(max_length=200)
    difficulty = models.CharField(max_length=1, choices=DIFFICULTY_CHOICES, default=DIFFICULTY_EASY)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title


class Question(models.Model):
    text = models.TextField()
    test = models.ForeignKey(Test, on_delete=models.CASCADE, related_name='questions')

    def __str__(self):
        return self.text


class Answer(models.Model):
    text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')

    def __str__(self):
        return self.text

class UserTestAttempt(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    incorrect_questions = models.ManyToManyField(Question) # Новое поле
    correct_answers = models.IntegerField()
    incorrect_answers = models.IntegerField()
    completed_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.user.username} - {self.test.title}'

quiz/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from .models import Test, UserTestAttempt, Answer


@login_required
def test_detail(request, pk):
    test = get_object_or_404(Test, pk=pk)
    if request.method == "POST":
        correct_answers = 0
        incorrect_answers = 0
        incorrect_questions = []

        for question in test.questions.all():
            answer = request.POST.get(str(question.pk))

            if answer is not None and question.answers.filter(pk=answer, is_correct=True).exists():
                correct_answers += 1
            else:
                incorrect_answers += 1
                incorrect_questions.append(question)

        attempt = UserTestAttempt(
            user=request.user,
            test=test,
            correct_answers=correct_answers,
            incorrect_answers=incorrect_answers,
        )
        print(attempt)
        attempt.save()
        
        for question in incorrect_questions:
            attempt.incorrect_questions.add(question)
        attempt.save()

        return redirect('quiz:test_result', pk=attempt.pk)

    return render(request, 'quiz/test_detail.html', {'test': test})




def test_list(request):
    tests = Test.objects.all()

    return render(request, 'quiz/test_list.html', {'tests': tests})


def test_result(request, pk):
    attempt = get_object_or_404(UserTestAttempt, pk=pk)
    return render(request, 'quiz/test_result.html', {'attempt': attempt})

def statistics(request):
    attempts = UserTestAttempt.objects.filter(user=request.user).order_by('-completed_at')
    return render(request, 'quiz/statistics.html', {'attempts': attempts})

quiz/templates/quiz/base.html
<!DOCTYPE html>
<html>
<head>
  <title>Авиационная безопасность</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">Авиационная безопасность</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav ml-auto">
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'articles:article_list' %}">Статьи</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'quiz:test_list' %}">Тесты</a>
      </li>
    </ul>
    
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.username }} <!-- Имя пользователя -->
        </button>
           
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            {% if request.user.is_authenticated %}
            
              <a class="dropdown-item" href="{% url 'accounts:profile' %}">Мой профиль</a>
              <a class="dropdown-item" href="{% url 'quiz:statistics' %}">Статистика</a>
              <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
            {% else %}
              <a class="dropdown-item" href="{% url 'login' %}">Войти</a>
              <a class="dropdown-item" href="{% url 'accounts:register' %}">Регистрация</a>
            {% endif %}
          </div>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
</body>
</html>

quiz/templates/quiz/statistics.html
{% extends "quiz/base.html" %}

{% block content %}
<h2 class="my-4">Моя статистика</h2>
{% for attempt in attempts %}
<div class="card mb-3">
    <div class="card-body">
        <h3 class="card-title">{{ attempt.test.title }}</h3>
        <p class="card-text">Верные ответы: {{ attempt.correct_answers }}</p>
        <p class="card-text">Неверные ответы: {{ attempt.incorrect_answers }}</p>
        <a href="{% url 'quiz:test_result' pk=attempt.pk %}" class="btn btn-primary">Посмотреть детали</a>
    </div>
</div>
{% empty %}
<p>Вы не прошли ни единого теста.</p>
{% endfor %}
{% endblock %}

quiz/templates/quiz/test_detail.html
{% extends "quiz/base.html" %}

{% block content %}
<h2 class="my-4">{{ test.title }}</h2>
<form method="post">
    {% csrf_token %}
    {% for question in test.questions.all %}
    <div class="card mb-3">
        <div class="card-body">
            <h3 class="card-title">{{ question.text }}</h3>
            {% for answer in question.answers.all %}
            <div class="form-check">
                <input class="form-check-input" type="radio" name="{{ question.id }}" value="{{ answer.id }}">
                <label class="form-check-label">{{ answer.text }}</label>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Отправить результат</button>
</form>
{% endblock %}

quiz/templates/quiz/test_list.html
{% extends "quiz/base.html" %}

{% block content %}
<h2 class="my-4">Список тестов</h2>
<div >
    <style>
        .card {
            margin-top: 10px;
        }
    </style>
    {% for test in tests %}
    <div class="m-1">
        <div class="card">
            
            <div class="card-body">
                <h5 class="card-title">
                    <a href="{% url 'quiz:test_detail' test.id %}">{{ test.title }}</a>
                </h5>
                <p class="card-text">Сложность: {{ test.get_difficulty_display }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

quiz/templates/quiz/test_result.html
{% extends 'quiz/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="my-4">Результаты теста</h2>

            <p>
                Вы ответили на {{ attempt.correct_answers }} вопросов верно и на {{ attempt.incorrect_answers }} вопросов неверно.
            </p>

            {% if attempt.incorrect_questions.all %}
                <h3 class="my-3">Вопросы, на которые был неверно дан ответ:</h3>
                <ul class="list-group">
                    {% for question in attempt.incorrect_questions.all %}
                        <li class="list-group-item">{{ question.text }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}