articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('<int:pk>/', views.article_detail, name='article_detail'),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

quizsite/urls.py
from os import name
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import logout_view

from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('articles/', include('articles.urls', namespace='articles')),
    path('logout/', logout_view, name='logout'),
    path('', include('quiz.urls', namespace='quiz')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Article(models.Model):
    title = models.CharField(max_length=200)
    cover_image = models.ImageField(upload_to='articles/covers/', null=True, blank=True)
    content = RichTextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='articles')

    def __str__(self):
        return self.title

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = RichTextField()
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created_at',)
    
    def __str__(self):
        return 'Comment by {} on {}'.format(self.author, self.article)

articles/forms.py
from django import forms
from .models import Comment
from ckeditor.widgets import CKEditorWidget

class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Comment
        fields = ('text',)

articles/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Comment
from django.shortcuts import render, redirect
from .forms import CommentForm
from django.contrib import messages

def article_list(request):
    articles = Article.objects.all()
    return render(request, 'articles/article_list.html', {'articles': articles})



def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comments = article.comments.order_by('-created_at')
   
    if request.method == 'POST':
        if not request.user.is_authenticated:
            messages.error(request, 'Вы должны быть авторизованы, чтобы оставить комментарий.')
            return redirect('accounts:register') # or the name of your login view
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем объект Comment, но пока не сохраняем в базу
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к текущей статье
            new_comment.article = article
            # Привязываем комментарий к текущему пользователю
            new_comment.author = request.user
            # Теперь можно сохранить комментарий в базу
            new_comment.save()
    else:
        comment_form = CommentForm()

    

    return render(request, 'articles/article_detail.html', {'article': article, 'comments': comments, 'comment_form': comment_form})

articles/templates/articles/article_detail.html
{% extends "quiz/base.html" %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8 col-lg-6">
        <h2>{{ article.title }}</h2>
        <p>Автор: {{ article.author.username }}</p>
        <p>{{ article.content | safe }}</p>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-12 col-md-8 col-lg-6">
        <h3>Комментарии</h3>
        {% for comment in comments %}
          <div class="card mb-3">
            <div class="card-body">
              <p class="card-text">{{ comment.text }}</p>
              <p class="card-text"><small class="text-muted">{{ comment.author.username }}</small></p>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-12 col-md-8 col-lg-6">
        <h3>Оставьте комментарий</h3>
        <form method="post">
          {% csrf_token %}
          <label for="id_text">Введите свой комментарий:</label>
          {{ comment_form.text }}
          <br>
          <button type="submit" class="btn btn-primary my-3">Отправить</button>
      </form>
      
      </div>
    </div>
  </div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends "quiz/base.html" %}

{% block content %}
  <div class="container">
    <h2 class="mt-3 mb-3">Статьи</h2>
    <div class="row">
      {% for article in articles %}
        <div class="col-md-4 mb-3">
          <div class="card">
            <img class="card-img-top" src="{{ article.cover_image.url }}" alt="Обложка статьи">
            <div class="card-body">
              <h5 class="card-title">{{ article.title }}</h5>
              <p class="card-text">{{ article.content|striptags|escape|truncatewords:10 }}</p>
              <a href="{% url 'articles:article_detail' article.id %}" class="btn btn-primary">Читать далее</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}